import * as fs from 'fs';
import * as path from 'path';
import { LAYER_META, LAYER_ORDER } from './layerMap';

const SECTIONS = [
    { num: 1, title: 'Module Overview' },
    { num: 2, title: 'Hardware / Peripheral' },
    { num: 3, title: 'Configuration' },
    { num: 4, title: 'Function Inventory' },
    { num: 5, title: 'Data Flow' },
    { num: 6, title: 'Cross-Module Dependencies' },
    { num: 7, title: 'Sequence Diagram' },
    { num: 8, title: 'State Machine' },
    { num: 9, title: 'Design Decisions' },
    { num: 10, title: 'Known Issues & TODOs' }
];

/**
 * Write a layout-only HTML shell for a module doc.
 * Session 3 will replace placeholder content with real LLM output.
 */
export function renderDocShell(
    moduleName: string,
    layerName: string,
    outputPath: string
): void {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    const html = buildDocHtml(moduleName, layerName);
    fs.writeFileSync(outputPath, html, 'utf8');
}

// ---------------------------------------------------------------------------

function getLayerColor(layer: string): string {
    return LAYER_META[layer]?.color ?? '#6e7681';
}

function getLayerBg(layer: string): string {
    const map: Record<string, string> = {
        'MCAL': '#0f0a1e',
        'CDD': '#1a0f00',
        'ESAL': '#001820',
        'SRVLayer': '#001a0f',
        'ASW': '#00112a'
    };
    return map[layer] ?? '#161b22';
}

function esc(s: string): string {
    return s
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function buildSidebarLinks(): string {
    return SECTIONS.map(s =>
        `<a href="#section-${s.num}" class="nav-link">${esc(s.num.toString().padStart(2, '0'))}. ${esc(s.title)}</a>`
    ).join('\n');
}

function buildStackWidget(activeLayer: string): string {
    const layerColor = getLayerColor(activeLayer);
    const layerBg = getLayerBg(activeLayer);
    let html = `
      <div class="stack-widget">
        <div class="stack-title">Stack Position</div>
        <div class="stack-item stack-hw">Hardware</div>
        <div class="stack-arrow">↓</div>`;

    for (let i = 0; i < LAYER_ORDER.length; i++) {
        const layer = LAYER_ORDER[i];
        const isActive = layer === activeLayer;
        const color = getLayerColor(layer);
        if (isActive) {
            html += `\n        <div class="stack-item stack-active" style="color:${color};border-left:2px solid ${color};background:${layerBg}">${esc(layer)}</div>`;
        } else {
            html += `\n        <div class="stack-item stack-inactive">${esc(layer)}</div>`;
        }
        if (i < LAYER_ORDER.length - 1) {
            html += `\n        <div class="stack-arrow">↓</div>`;
        }
    }

    html += `\n      </div>`;
    return html;
}

function buildSections(): string {
    return SECTIONS.map(s => {
        const numPadded = s.num.toString().padStart(2, '0');
        return `
    <section id="section-${s.num}" class="doc-section">
      <div class="section-heading">
        <span class="section-num">${numPadded}</span>
        <h2>${esc(s.title)}</h2>
      </div>
      <div class="section-body">
        <p class="placeholder-text">Content will be generated by GitHub Copilot in Session 3.</p>
      </div>
      <hr class="section-rule" />
    </section>`;
    }).join('\n');
}

function buildDocHtml(moduleName: string, layerName: string): string {
    const layerColor = getLayerColor(layerName);
    const layerBg = getLayerBg(layerName);
    const timestamp = new Date().toLocaleString('en-GB', {
        year: 'numeric', month: 'short', day: '2-digit',
        hour: '2-digit', minute: '2-digit'
    });

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(moduleName)} — BMS Design Doc</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet" />
  <style>
    html { scroll-behavior: smooth; }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'JetBrains Mono', 'Consolas', monospace;
      background: #0d1117;
      color: #e6edf3;
    }

    /* ── FIXED TOP BAR ── */
    #topbar {
      position: fixed;
      top: 0; left: 0; right: 0;
      height: 56px;
      background: #161b22;
      border-bottom: 1px solid #30363d;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 24px;
      z-index: 100;
    }

    .topbar-brand {
      font-size: 0.78rem;
      color: #58a6ff;
      letter-spacing: 0.2em;
      text-transform: uppercase;
    }

    .topbar-center {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 3px;
    }

    .topbar-module {
      font-size: 1rem;
      font-weight: 600;
      color: #e6edf3;
    }

    .layer-badge {
      font-size: 0.72rem;
      font-weight: 500;
      padding: 2px 10px;
      border-radius: 10px;
      border: 1px solid ${layerColor};
      color: ${layerColor};
      background: ${layerBg};
    }

    .topbar-right {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .topbar-ts {
      font-size: 0.78rem;
      color: #8b949e;
    }

    .btn-open {
      background: transparent;
      border: 1px solid #30363d;
      color: #8b949e;
      font-family: 'JetBrains Mono', monospace;
      font-size: 0.78rem;
      border-radius: 6px;
      padding: 4px 12px;
      cursor: pointer;
      transition: color 150ms, border-color 150ms;
    }
    .btn-open:hover { color: #e6edf3; border-color: #8b949e; }

    /* ── FIXED LEFT SIDEBAR ── */
    #sidebar {
      position: fixed;
      top: 56px; left: 0; bottom: 0;
      width: 220px;
      background: #010409;
      border-right: 1px solid #21262d;
      overflow-y: auto;
      padding: 20px 0;
      display: flex;
      flex-direction: column;
    }

    .nav-title {
      color: #484f58;
      font-size: 0.68rem;
      letter-spacing: 0.18em;
      text-transform: uppercase;
      padding: 0 16px;
      margin-bottom: 16px;
    }

    .nav-link {
      display: block;
      padding: 7px 16px;
      color: #6e7681;
      font-size: 0.82rem;
      text-decoration: none;
      border-left: 2px solid transparent;
      transition: all 150ms;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .nav-link:hover { color: #c9d1d9; }
    .nav-link.active {
      color: #e6edf3;
      border-left-color: #58a6ff;
      background: rgba(88, 166, 255, 0.07);
    }

    /* ── STACK WIDGET ── */
    .stack-widget {
      margin-top: auto;
      padding: 20px 16px;
      border-top: 1px solid #21262d;
    }

    .stack-title {
      color: #484f58;
      font-size: 0.65rem;
      text-transform: uppercase;
      letter-spacing: 0.15em;
      margin-bottom: 10px;
    }

    .stack-item {
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      margin: 1px 0;
      border-left: 2px solid transparent;
    }

    .stack-hw { color: #484f58; }
    .stack-inactive { color: #484f58; }
    .stack-active { font-weight: 600; }

    .stack-arrow {
      color: #30363d;
      font-size: 0.7rem;
      padding-left: 8px;
      line-height: 1.4;
    }

    /* ── MAIN CONTENT ── */
    #content {
      margin-left: 220px;
      padding-top: 56px;
      min-height: 100vh;
      background: #0d1117;
    }

    .content-inner {
      max-width: 860px;
      padding: 40px 48px;
      margin: 0 auto;
    }

    /* ── SECTIONS ── */
    .doc-section { margin-bottom: 8px; }

    .section-heading {
      display: flex;
      align-items: baseline;
      gap: 16px;
      margin-bottom: 20px;
    }

    .section-num {
      font-family: 'JetBrains Mono', monospace;
      font-size: 1.8rem;
      color: #58a6ff;
      opacity: 0.35;
      font-weight: 700;
      line-height: 1;
    }

    .section-heading h2 {
      color: #e6edf3;
      font-size: 1.25rem;
      font-weight: 600;
      margin: 0;
      scroll-margin-top: 76px;
    }

    .section-body {
      color: #8b949e;
      line-height: 1.8;
      font-size: 0.93rem;
    }

    .placeholder-text {
      color: #30363d;
      font-style: italic;
      border-left: 2px solid #21262d;
      padding-left: 12px;
    }

    .section-rule {
      border: none;
      border-top: 1px solid #21262d;
      margin: 36px 0;
    }

    /* ── FOOTER ── */
    #footer {
      text-align: center;
      color: #484f58;
      font-size: 0.78rem;
      padding: 40px 0 32px;
      border-top: 1px solid #21262d;
      margin-top: 48px;
    }

    /* ── SCROLLBAR ── */
    ::-webkit-scrollbar { width: 5px; height: 5px; }
    ::-webkit-scrollbar-track { background: #010409; }
    ::-webkit-scrollbar-thumb { background: #30363d; border-radius: 3px; }
  </style>
</head>
<body>

  <!-- Fixed top bar -->
  <header id="topbar">
    <div class="topbar-brand">⚡ BMS DocGen</div>
    <div class="topbar-center">
      <div class="topbar-module">${esc(moduleName)}</div>
      <div class="layer-badge">${esc(layerName)}</div>
    </div>
    <div class="topbar-right">
      <span class="topbar-ts">Generated ${esc(timestamp)}</span>
      <button class="btn-open" onclick="window.open(window.location.href)">Open in Browser</button>
    </div>
  </header>

  <!-- Fixed left sidebar -->
  <nav id="sidebar">
    <div class="nav-title">Contents</div>
    ${buildSidebarLinks()}
    ${buildStackWidget(layerName)}
  </nav>

  <!-- Main content -->
  <main id="content">
    <div class="content-inner">
      ${buildSections()}
      <footer id="footer">
        Generated by ⚡ BMS DocGen &middot; ${esc(timestamp)} &middot; Powered by GitHub Copilot
      </footer>
    </div>
  </main>

  <script>
    // Sidebar active link tracking
    const sections = document.querySelectorAll('.doc-section');
    const links = document.querySelectorAll('#sidebar .nav-link');

    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          links.forEach(l => l.classList.remove('active'));
          const id = entry.target.id;
          const link = document.querySelector('#sidebar a[href="#' + id + '"]');
          if (link) { link.classList.add('active'); }
        }
      });
    }, { rootMargin: '-20% 0px -70% 0px' });

    sections.forEach(s => observer.observe(s));
  </script>
</body>
</html>`;
}
